name: Latest Posts
on:
  schedule:
    - cron: '0 0 * * *' # Runs every hour
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-posts:
    name: Update README with latest posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://esequeira.com/index.xml"
